### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by cricket007** [cricket007/schema-registry-transfer-smt#1]
This was tested (using MirrorTool, as mentioned in the README) between a deployed environment and local Confluent Platform Docker Compose stack. 

Ideally, real unit tests should be added. 

1. Have independent Kafka w/ Schema Registry, `cluster1`, and `cluster2`. Or just mock two registries backed by a HashMap. 
2. Push at least 2 Avro schemas to `cluster1`.  `{schema1, schema2}`
3. Invoke `copySchemas` functions of the Transform class to copy `schema2` from source to destination. 
4. Verify `cluster2` registry has a schema, that it is the same, and that the ID would be different because the destination registry was initially empty. 
5. (If testing Kafka clients e2e) Create topics on `cluster2` and consume from them. These should match records that are produced to `cluster1`

**Comment by ertaoxu** [comment]
Do you have complete configure for expamle?

**Comment by cricket007** [comment]
@ertaoxu This project is only a transformation, and all relevant configurations are mentioned in the README.

You will need to combine the properties with a separate project for the `connector.class` and any properties for that connector
