### ISSUE TITLE
Basic HTTP Authentication Support

### ISSUE THREAD

**Issue by jheinnic** [cricket007/schema-registry-transfer-smt#14]
We're currently blocked in our effort to use Schema Registry Transfer SMT to provide mirroring functionality to a handful of Avro-enabled Confluent Kafka topics.  Exploratory work combing this SMT with Comcast's Mirror Tool project has been promising, but in production we use a third party provider that implements a Basic HTTP Authentication requirement on their schema registry.

The root cause seems to be that `schema-registry-transfer-smt` is not propagating any properties from its own input configuration to a properties hash on either the source or target embedded schema registry clients.  There is no way to set `basic.auth.credentials.source` to `USER_INFO` and provide a `basic.auth.user.info` property that carries the credentials.

Curiously, the default behavior for `basic.auth.credentials.source` is `URL`, which supports passing credentials in the schema registry URL value itself, which normally has a form like `http(s)://<host>:<port>/`, by inserting them before the host:port combination followed by an `@`, like this: `http(s)://<username>:<password>@<host>:<port>/`.  Unfortunately, this default behavior only seems to apply if the schema registry client is given a properties map--it does not seem to work when the third constructor argument for that hash is not even used.

So, even just passing in an empty `HashMap` to the schema registry client constructors would likely unblock `URL` style authentication, which is better than nothing.  In our case, it is somewhat difficult to combine the URL with the access credentials from a matter of secrets protection.  Our deployment process would benefit greatly from being able to use `USER_INFO` as a credential source.  It would be ideal if `schema-registry-transfer-smt` accepted a pair of the two required properties prefixed by either `src.` or `dest.` and then stripped the prefix away while routing the remaining property name and its value to a config HashMap for the appropriate embedded client.

For example, the following four properties might be used to configure access credentials for both clients appropriately:

`{
    ...,
    "src.basic.auth.credentials.source": "USER_INFO",
    "src.basic.auth.user.info": "srcuser:srcpassword",
    "dest.basic.auth.credentials.source": "USER_INFO",
    "dest.basic.auth.user.info": "destuser:destpassword",
    ...
}`

**Comment by cricket007** [comment]
Closed by #15
