### ISSUE TITLE
Uber Jar Blocks Basic HTTP Authentication

### ISSUE THREAD

**Issue by jheinnic** [cricket007/schema-registry-transfer-smt#16]
Now that the SMT build includes code for HTTP Basic Authentication, we were able to complete the path to loading a jar with the changes to our development K8s cluster and, from there, an instance of Kafka Connect.  Unfortunately, the were were still unable to complete a Basic HTTP Authentication, despite test cases implemented here that suggested all should be working fine.

Investigating the issue turned up two root causes, only one of which had a short-term workaround.  The issue that we could not work around did not manifest in the test suite because the tests are evaluated before the Maven shade plugin has relocated the Schema Registry client code from `io.confluent` to `cricket.jmoore.confluent`.

The relocation is an issue because the shade plugin is currently not configured to apply transformations specific to Java's `ServiceProvider` extension mechanism.  The Basic HTTP Authentication modules are implemented using this mechanism, so once relocated the `/META-INF/services/io.confluent.kafka.schemaregistry.client.security.basicauth.BasicAuthCredentialProvider` file from `schema-registry-client.jar` no longer enumerates the three strategy implementations, one for each of the three possible configurable values for `basic.auth.credentials.source`.  Since no implementation for any of the defined authentication strategies is found, the relocated client simply ignores otherwise valid authentication specification properties.

The simple correction is to add a directive to the Maven Shade plugin's configuration that informs it the relocated jar contains Service Providers.  It then takes care of renaming the file under `/META-INF/services` and changing each line entry as well, after which the client is able to locate its implementation classes.

**Comment by cricket007** [comment]
Handled by #17 ?

**Comment by jheinnic** [comment]
Yes indeed.  This was the tougher of the two issues to identify, but the easier to fix.  I submitted a partial PR for the other one that includes a failing test case illustrating the problem, but have not yet created its corresponding issue yet, although I did describe the issue in that PR's comments already.
