### ISSUE TITLE
[Feature Request] Support for multiple source schema registries

### ISSUE THREAD

**Issue by twiechert** [cricket007/schema-registry-transfer-smt#23]
Consider the case where the smt is used by replicator consuming different topics that contain messages registered with different schema registries.

Currently, we workaround this by having multiple connect configs with different smts attached.

I think it would be nice to be able to pass a pattern based mapping for registries.

```
department_a_events * --> schema reg A
department_b_events* --> schema reg B
```
Config wise:
```
transforms.AvroSchemaTransfer.dest.schema.registry.urls=[http://schema-registry-2:8081, http://schema-registry-3:8081]
transforms.AvroSchemaTransfer.dest.schema.registry.topic.mappings=[department_a_events *, department_b_events *]
```
What do you think? I guess I would be able to provide a PR for this. I would suggest to keep the existing properties as they are and use 

```
transforms.AvroSchemaTransfer.dest.schema.registry.url=http://schema-registry-2:8081
```

as fallback if none of  the patterns matches

**Comment by cricket007** [comment]
> pass a pattern based mapping for registries

My main concern would be what if you had N registries and M topic patterns where N != M ? How would that mapping line up?

I personally see nothing wrong with having separate connect tasks for separate topics configured for different registries.

**Comment by twiechert** [comment]
> My main concern would be what if you had N registries and M topic patterns where N != M ? How would that mapping line up?

One would need to force a 1:1 mapping so that n=m, repeating entries potentially.

Now I am uncertain myself :). In our setup I planned to organize the connect replicators by domain, instead I'm finding myself in a situation where replicators are split by the source registry. This also means that there are configs for a single topic only.

But, yes, I do understand that this feature might be considered overkill and bloats the config api.

**Comment by cricket007** [comment]
> replicators are split by the source registry. This also means that there are configs for a single topic only.

I think one benefit to this is that the error handling is simpler and isloated if a task fails to contact the registry. 

Besides that, see "`Mistake #2`" 😃  
https://www.confluent.io/blog/17-ways-to-mess-up-self-managed-schema-registry

**Comment by twiechert** [comment]
Convinced. Let's close it :)

Well, of course it makes sense to have a central schema registry. Bu as you know, sometimes it is weird political circumstances that lead to such violations.
